CREATE TABLE `aiAnalysisLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`entityType` enum('customer','subsidiary','opportunity','deal','news') NOT NULL,
	`entityId` int NOT NULL,
	`analysisType` varchar(64) NOT NULL,
	`prompt` text,
	`response` text,
	`status` enum('pending','completed','failed') DEFAULT 'pending',
	`requestedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `aiAnalysisLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`globalOneId` varchar(64),
	`name` varchar(255) NOT NULL,
	`registeredName` varchar(255),
	`localName` varchar(255),
	`tradeName` varchar(255),
	`industry` varchar(128),
	`industryCode` varchar(32),
	`businessType` varchar(128),
	`foundedDate` varchar(32),
	`operatingStatus` enum('active','inactive','dissolved','unknown') DEFAULT 'active',
	`isIndependent` boolean DEFAULT true,
	`registrationCountry` varchar(64),
	`registrationAddress` text,
	`registrationNumber` varchar(64),
	`registrationType` varchar(64),
	`website` varchar(255),
	`phone` varchar(64),
	`email` varchar(255),
	`capitalAmount` bigint,
	`capitalCurrency` varchar(8) DEFAULT 'USD',
	`annualRevenue` bigint,
	`revenueCurrency` varchar(8) DEFAULT 'USD',
	`revenueYear` varchar(8),
	`employeeCount` int,
	`stockExchange` varchar(32),
	`stockSymbol` varchar(16),
	`riskLevel` enum('low','medium','high','unknown') DEFAULT 'unknown',
	`riskDescription` text,
	`ceoName` varchar(128),
	`ceoTitle` varchar(128),
	`tags` text,
	`logoUrl` varchar(512),
	`description` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `customers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dataImports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileType` enum('excel','word','csv','json') NOT NULL,
	`fileUrl` varchar(512),
	`fileSize` int,
	`status` enum('pending','processing','completed','failed') DEFAULT 'pending',
	`totalRows` int,
	`successRows` int,
	`failedRows` int,
	`fieldMapping` text,
	`errorLog` text,
	`importedBy` int,
	`importedByName` varchar(128),
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dataImports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`subsidiaryId` int,
	`opportunityId` int,
	`dealNumber` varchar(64),
	`name` varchar(255) NOT NULL,
	`description` text,
	`amount` bigint NOT NULL,
	`currency` varchar(8) DEFAULT 'USD',
	`monthlyRecurring` bigint,
	`oneTimeFee` bigint,
	`productType` varchar(128),
	`productCategory` varchar(128),
	`contractStartDate` timestamp,
	`contractEndDate` timestamp,
	`contractDurationMonths` int,
	`status` enum('active','completed','cancelled','renewed') DEFAULT 'active',
	`closedDate` timestamp,
	`closedBy` int,
	`closedByName` varchar(128),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `newsItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`subsidiaryId` int,
	`title` varchar(512) NOT NULL,
	`summary` text,
	`content` text,
	`sourceUrl` varchar(1024),
	`sourceName` varchar(128),
	`publishedDate` timestamp,
	`fetchedDate` timestamp DEFAULT (now()),
	`aiAnalysis` text,
	`aiAnalyzedAt` timestamp,
	`category` varchar(64),
	`sentiment` enum('positive','neutral','negative','unknown') DEFAULT 'unknown',
	`relevanceScore` int,
	`isHighlight` boolean DEFAULT false,
	`isRead` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `newsItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `opportunities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`subsidiaryId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`stage` enum('lead','qualified','proposal','negotiation','closed_won','closed_lost') DEFAULT 'lead',
	`status` enum('active','on_hold','cancelled') DEFAULT 'active',
	`probability` int DEFAULT 0,
	`amount` bigint,
	`currency` varchar(8) DEFAULT 'USD',
	`productType` varchar(128),
	`productCategory` varchar(128),
	`expectedCloseDate` timestamp,
	`createdDate` timestamp DEFAULT (now()),
	`lastActivityDate` timestamp,
	`sourceType` varchar(64),
	`sourceDetail` varchar(255),
	`ownerId` int,
	`ownerName` varchar(128),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `opportunities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `subsidiaries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`parentSubsidiaryId` int,
	`globalOneId` varchar(64),
	`name` varchar(255) NOT NULL,
	`localName` varchar(255),
	`entityType` enum('subsidiary','branch','affiliate','joint_venture','division') DEFAULT 'subsidiary',
	`ownershipPercentage` int,
	`country` varchar(64),
	`region` varchar(64),
	`city` varchar(64),
	`address` text,
	`industry` varchar(128),
	`operatingStatus` enum('active','inactive','dissolved','unknown') DEFAULT 'active',
	`employeeCount` int,
	`annualRevenue` bigint,
	`revenueCurrency` varchar(8) DEFAULT 'USD',
	`relationshipType` enum('customer','supplier','both','none') DEFAULT 'customer',
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subsidiaries_id` PRIMARY KEY(`id`)
);
